In [1]:
import numpy as np

In [2]:
# Built-in Matemetical Functions

arr = np.array([3,3,25,2])
arr

array([ 3,  3, 25,  2])

In [3]:
np.mean(arr)

np.float64(8.25)

In [4]:
np.std(arr)

np.float64(9.67923034130297)

In [5]:
np.var(arr)

np.float64(93.6875)

In [6]:
np.min(arr)

np.int64(2)

In [7]:
np.sum(arr)

np.int64(33)

In [8]:
np.prod(arr)

np.int64(450)

In [9]:
np.median(arr)

np.float64(3.0)

In [10]:
np.percentile(arr, 50)

np.float64(3.0)

In [11]:
np.argmin(arr)

np.int64(3)

In [12]:
np.argmax(arr)

np.int64(2)

In [14]:
np.unique(arr)

array([ 2,  3, 25])

In [15]:
np.diff(arr)

array([  0,  22, -23])

In [16]:
np.cumsum(arr)

array([ 3,  6, 31, 33])

In [17]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.log(arr)

array([1.09861229, 1.09861229, 3.21887582, 0.69314718])

In [19]:
np.exp(arr)

array([2.00855369e+01, 2.00855369e+01, 7.20048993e+10, 7.38905610e+00])