In [1]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.sum(arr,axis=0)   # sum along rows

array([12, 15, 18])

In [5]:
np.sum(arr,axis=1)   # sum along columns

array([ 6, 15, 24])

In [6]:
# Multidimensional Arrays

arr[0][1]   #arr[row index][col index]

np.int64(2)

In [8]:
arr[0:2, 1:4]

array([[2, 3],
       [5, 6]])

In [11]:
# Indexing in 3D Arrays

arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

In [12]:
arr3D.shape

(2, 2, 3)

In [13]:
arr3D[0, 1, 2]

np.int64(6)

In [14]:
arr3D[:, 0, :]

array([[1, 2, 3],
       [7, 8, 9]])

In [15]:
arr[:, 0]    # all rows of 1st column

array([1, 4, 7])

In [16]:
arr3D[:, 0, :]   # first row from each "sheet" in a 3D array

array([[1, 2, 3],
       [7, 8, 9]])

In [18]:
# changing data along an axis

arr[:, 1] = 0   # Replace all elements in column 1 with 0

In [19]:
arr

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])