In [9]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4,5])

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
arr.dtype

dtype('int64')

In [14]:
# Vectorization

result= arr + 2     # Vectorization allows you to perform operations on entire arrays at once, instead of iterating over elements one by one.(fixes loop problem)
result

array([3, 4, 5, 6, 7])

In [24]:
# Broadcasting a 2D Array and a 1D Array
"""enables operations between arrays of different shapes by automatically stretching the smaller array to match the shape of the larger array, without creating additional copies."""

arr1 = np.array([[1,2,3],[5,6,7]])
arr2 = np.array([1,2,3])
res = arr1 + arr2

In [22]:
res

array([[ 2,  4,  6],
       [ 6,  8, 10]])

In [26]:
# Simulating a dataset (5 samples, 3 features)

data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

mean = data.mean(axis=0)   # Calculating mean and standard deviation for each feature (column)
std = data.std(axis=0)

normalized_data = (data - mean) / std   # Normalizing the data using broadcasting

normalized_data

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])