In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
myarr.shape   # prints shape of array(rows,columns)

(3, 3)

In [5]:
myarr.size    # prints total elements

9

In [7]:
myarr.ndim    # prints dimension

2

In [8]:
myarr.dtype   # prints the data type

dtype('int64')

In [9]:
myarr.astype('float64')   # changing data type

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [25]:
myarr.reshape((1,9))   # reshapes the array

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
myarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])