In [2]:
import numpy as np

In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [4]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [7]:
flat = arr.flatten()

In [8]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [9]:
flat[0]     # flat[index]

np.int64(1)

In [10]:
flat[5]

np.int64(6)

In [11]:
flat[:4]    # [from:to]

array([1, 2, 3, 4])

In [13]:
flat[5:9]

array([6, 7, 8, 9])

In [14]:
flat[::3]   # every 3rd element

array([ 1,  4,  7, 11])

In [15]:
idx = [0,2,5]  # multiple indices to select

In [16]:
idx

[0, 2, 5]

In [17]:
arr[arr>3]   # condition : values greater than 3

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])